package example

type SubOrderList struct {
	SubOrderList []SubOrder `json:"orders"`
}

type SubOrder struct {
	AccurateAcreage         float64         `json:"accurateAcreage"`
	Acreage                 float64         `json:"acreage"`
	AcreageLeafActives      float64         `json:"acreageLeafActives"`
	AcreageLeafBrights      int             `json:"acreageLeafBrights"`
	AttechImgs              string          `json:"attechImgs"`
	Bale                    string          `json:"bale"`
	BrandAttachedID         string          `json:"brandAttachedID"`
	BrandAttachedName       string          `json:"brandAttachedName"`
	BrandID                 string          `json:"brandID"`
	BrandName               string          `json:"brandName"`
	ColorIDs                string          `json:"colorIDs"`
	ColorLabel              string          `json:"colorLabel"`
	DescsGlassHole          []any           `json:"descsGlassHole"`
	DescsMetalBase          []string        `json:"descsMetalBase"`
	DescsMetalReal          []string        `json:"descsMetalReal"`
	DescsOriGlassHole       []any           `json:"descsOriGlassHole"`
	FrameLabel              string          `json:"frameLabel"`
	FrameNumber             string          `json:"frameNumber"`
	GoodsAccurateAcreage    float64         `json:"goods_accurateAcreage"`
	GoodsAcreage            float64         `json:"goods_acreage"`
	HasStickFan             bool            `json:"hasStickFan"`
	Height                  int             `json:"height"`
	HoleNumber              string          `json:"holeNumber"`
	Info                    Info            `json:"info"`
	InfosMetalAll           []InfosMetalAll `json:"infosMetalAll"`
	Items                   string          `json:"items"`
	LabelsFanGlass          []string        `json:"labelsFanGlass"`
	LabelsFanYarn           []string        `json:"labelsFanYarn"`
	LabelsGlassBottom       []string        `json:"labelsGlassBottom"`
	LabelsGlassDefault      []string        `json:"labelsGlassDefault"`
	LabelsGlassMiddle       []any           `json:"labelsGlassMiddle"`
	LabelsGlassName         []string        `json:"labelsGlassName"`
	LabelsGlassTop          []string        `json:"labelsGlassTop"`
	LabelsLeafActive        []string        `json:"labelsLeafActive"`
	LabelsMetalAll          []string        `json:"labelsMetalAll"`
	LabelsMetalColorAll     []string        `json:"labelsMetalColorAll"`
	LabelsMetalColorGauze   []any           `json:"labelsMetalColorGauze"`
	LabelsMetalColorGlass   []string        `json:"labelsMetalColorGlass"`
	LabelsMetalColorYarn    []string        `json:"labelsMetalColorYarn"`
	LabelsMetalGauze        []any           `json:"labelsMetalGauze"`
	LabelsMetalGlass        []string        `json:"labelsMetalGlass"`
	LabelsMetalOffsetGround []int           `json:"labelsMetalOffsetGround"`
	LabelsMetalPack         []string        `json:"labelsMetalPack"`
	LabelsMetalTotal        []string        `json:"labelsMetalTotal"`
	LabelsMetalYarn         []string        `json:"labelsMetalYarn"`
	LabelsTechnics          []string        `json:"labelsTechnics"`
	Length                  int             `json:"length"`
	MemosGlass              []string        `json:"memosGlass"`
	MemosTechnics           []any           `json:"memosTechnics"`
	MultiColor              bool            `json:"multiColor"`
	NamesFanGlass           []string        `json:"namesFanGlass"`
	NamesFanYarn            []string        `json:"namesFanYarn"`
	NumCornersAttach        int             `json:"numCornersAttach"`
	NumFanGauzes            int             `json:"numFanGauzes"`
	NumFanGlasses           int             `json:"numFanGlasses"`
	NumFanYarns             int             `json:"numFanYarns"`
	NumLeafActives          int             `json:"numLeafActives"`
	NumLeafBrights          int             `json:"numLeafBrights"`
	NumLeafBrightsExcCel    int             `json:"numLeafBrightsExcCel"`
	Pack                    Pack            `json:"pack"`
	PackDesc                string          `json:"packDesc"`
	PartID                  string          `json:"partID"`
	PassValidate            int             `json:"passValidate"`
	ProductID               string          `json:"productID"`
	ProductName             string          `json:"productName"`
	SegmentsHorizontal      string          `json:"segmentsHorizontal"`
	SegmentsVertical        string          `json:"segmentsVertical"`
	SeriesID                string          `json:"seriesID"`
	SeriesName              string          `json:"seriesName"`
	ThumbBytes              string          `json:"thumbBytes"`
	TopviewBytes            string          `json:"topviewBytes"`
	Type                    string          `json:"type"`
	WallThickness           int             `json:"wallThickness"`
	Width                   int             `json:"width"`
}
type InfosMetalAll struct {
	Bale             string  `json:"bale"`
	CategoryLabel    string  `json:"categoryLabel"`
	DisplayMode      bool    `json:"displayMode"`
	FanLabel         string  `json:"fanLabel"`
	FanMatH          int     `json:"fanMatH"`
	FanMatW          int     `json:"fanMatW"`
	FanOpenMode      int     `json:"fanOpenMode"`
	FanOpenModeLabel string  `json:"fanOpenModeLabel"`
	FanSplit         int     `json:"fanSplit"`
	FanTrack         int     `json:"fanTrack"`
	FanType          int     `json:"fanType"`
	HostBale         string  `json:"hostBale"`
	IsPackMain       int     `json:"isPackMain"`
	MaterialType     int     `json:"materialType"`
	MaterialTypeName string  `json:"materialTypeName"`
	MetalColor       string  `json:"metalColor"`
	MetalPackID      string  `json:"metalPackID"`
	MetalType        int     `json:"metalType"`
	OffsetCenter     int     `json:"offsetCenter"`
	OffsetFanBottom  int     `json:"offsetFanBottom"`
	OffsetGround     int     `json:"offsetGround"`
	OffsetSectionTop int     `json:"offsetSectionTop"`
	OffsetWindowSill int     `json:"offsetWindowSill"`
	Orient           int     `json:"orient"`
	PackLabel        string  `json:"packLabel"`
	PartID           string  `json:"partID"`
	Position         string  `json:"position"`
	Price            float64 `json:"price"`
	ProfileID        string  `json:"profileID"`
	ProfileName      string  `json:"profileName"`
	ProfileNumber    string  `json:"profileNumber"`
	ProfileTypeID    int     `json:"profileTypeID"`
	ProfileTypeName  string  `json:"profileTypeName"`
}
type Frames struct {
	AccurateAcreage         float64         `json:"accurateAcreage"`
	Acreage                 float64         `json:"acreage"`
	AcreageLeafActives      float64         `json:"acreageLeafActives"`
	AcreageLeafBrights      int             `json:"acreageLeafBrights"`
	Bale                    string          `json:"bale"`
	BrandAttachedID         string          `json:"brandAttachedID"`
	BrandAttachedName       string          `json:"brandAttachedName"`
	BrandID                 string          `json:"brandID"`
	BrandName               string          `json:"brandName"`
	ColorIDs                string          `json:"colorIDs"`
	ColorLabel              string          `json:"colorLabel"`
	DescsGlassHole          string          `json:"descsGlassHole"`
	DescsMetalBase          string          `json:"descsMetalBase"`
	DescsMetalReal          string          `json:"descsMetalReal"`
	DescsOriGlassHole       string          `json:"descsOriGlassHole"`
	FrameLabel              string          `json:"frameLabel"`
	FrameNumber             string          `json:"frameNumber"`
	HasStickFan             bool            `json:"hasStickFan"`
	Height                  int             `json:"height"`
	InfosMetalAll           []InfosMetalAll `json:"infosMetalAll"`
	LabelsFanGlass          string          `json:"labelsFanGlass"`
	LabelsFanYarn           string          `json:"labelsFanYarn"`
	LabelsGlassBottom       string          `json:"labelsGlassBottom"`
	LabelsGlassDefault      string          `json:"labelsGlassDefault"`
	LabelsGlassMiddle       string          `json:"labelsGlassMiddle"`
	LabelsGlassName         string          `json:"labelsGlassName"`
	LabelsGlassTop          string          `json:"labelsGlassTop"`
	LabelsLeafActive        string          `json:"labelsLeafActive"`
	LabelsMetalAll          string          `json:"labelsMetalAll"`
	LabelsMetalColorAll     string          `json:"labelsMetalColorAll"`
	LabelsMetalColorGauze   string          `json:"labelsMetalColorGauze"`
	LabelsMetalColorGlass   string          `json:"labelsMetalColorGlass"`
	LabelsMetalColorYarn    string          `json:"labelsMetalColorYarn"`
	LabelsMetalGauze        string          `json:"labelsMetalGauze"`
	LabelsMetalGlass        string          `json:"labelsMetalGlass"`
	LabelsMetalOffsetGround string          `json:"labelsMetalOffsetGround"`
	LabelsMetalPack         string          `json:"labelsMetalPack"`
	LabelsMetalTotal        string          `json:"labelsMetalTotal"`
	LabelsMetalYarn         string          `json:"labelsMetalYarn"`
	LabelsTechnics          string          `json:"labelsTechnics"`
	Length                  int             `json:"length"`
	MemosGlass              string          `json:"memosGlass"`
	MemosTechnics           string          `json:"memosTechnics"`
	MultiColor              bool            `json:"multiColor"`
	NamesFanGlass           string          `json:"namesFanGlass"`
	NamesFanYarn            string          `json:"namesFanYarn"`
	NumCornersAttach        int             `json:"numCornersAttach"`
	NumFanGauzes            int             `json:"numFanGauzes"`
	NumFanGlasses           int             `json:"numFanGlasses"`
	NumFanYarns             int             `json:"numFanYarns"`
	NumLeafActives          int             `json:"numLeafActives"`
	NumLeafBrights          int             `json:"numLeafBrights"`
	NumLeafBrightsExcCel    int             `json:"numLeafBrightsExcCel"`
	PartID                  string          `json:"partID"`
	PassValidate            int             `json:"passValidate"`
	ProductID               string          `json:"productID"`
	ProductName             string          `json:"productName"`
	SegmentsHorizontal      string          `json:"segmentsHorizontal"`
	SegmentsVertical        string          `json:"segmentsVertical"`
	SeriesID                string          `json:"seriesID"`
	SeriesName              string          `json:"seriesName"`
	Type                    string          `json:"type"`
	Width                   int             `json:"width"`
}
type Variables struct {
}
type Info struct {
	AccessHisLengthOne      any             `json:"accessHisLengthOne"`
	AccessHisLengthSum      int             `json:"accessHisLengthSum"`
	AccessHisPriceOne       any             `json:"accessHisPriceOne"`
	AccessHisPriceSum       int             `json:"accessHisPriceSum"`
	AccessLensPriceOne      any             `json:"accessLensPriceOne"`
	AccessLensPriceSum      int             `json:"accessLensPriceSum"`
	AcreageFrames           float64         `json:"acreageFrames"`
	AcreageLeafActives      float64         `json:"acreageLeafActives"`
	AcreageLeafBrights      int             `json:"acreageLeafBrights"`
	Btbs                    int             `json:"btbs"`
	Btwz                    string          `json:"btwz"`
	Corners                 []any           `json:"corners"`
	Cthigh                  int             `json:"cthigh"`
	DescsGlassHole          string          `json:"descsGlassHole"`
	DescsMetalBase          string          `json:"descsMetalBase"`
	DescsMetalReal          string          `json:"descsMetalReal"`
	DescsOriGlassHole       string          `json:"descsOriGlassHole"`
	Frames                  []Frames        `json:"frames"`
	GlassHeavyOne           float64         `json:"glassHeavyOne"`
	GlassHeavySum           float64         `json:"glassHeavySum"`
	GlassWeightAcc          float64         `json:"glassWeightAcc"`
	HasStickFan             bool            `json:"hasStickFan"`
	HeavyNoStripSum         float64         `json:"heavyNoStripSum"`
	InfosMetalAll           []InfosMetalAll `json:"infosMetalAll"`
	Kzqh                    int             `json:"kzqh"`
	LabelsFanGlass          string          `json:"labelsFanGlass"`
	LabelsFanYarn           string          `json:"labelsFanYarn"`
	LabelsFrame             string          `json:"labelsFrame"`
	LabelsGlassBottom       string          `json:"labelsGlassBottom"`
	LabelsGlassDefault      string          `json:"labelsGlassDefault"`
	LabelsGlassMiddle       string          `json:"labelsGlassMiddle"`
	LabelsGlassName         string          `json:"labelsGlassName"`
	LabelsGlassTop          string          `json:"labelsGlassTop"`
	LabelsLeafActive        string          `json:"labelsLeafActive"`
	LabelsMetalAll          string          `json:"labelsMetalAll"`
	LabelsMetalColorAll     string          `json:"labelsMetalColorAll"`
	LabelsMetalColorGauze   string          `json:"labelsMetalColorGauze"`
	LabelsMetalColorGlass   string          `json:"labelsMetalColorGlass"`
	LabelsMetalColorYarn    string          `json:"labelsMetalColorYarn"`
	LabelsMetalGauze        string          `json:"labelsMetalGauze"`
	LabelsMetalGlass        string          `json:"labelsMetalGlass"`
	LabelsMetalOffsetGround string          `json:"labelsMetalOffsetGround"`
	LabelsMetalPack         string          `json:"labelsMetalPack"`
	LabelsMetalTotal        string          `json:"labelsMetalTotal"`
	LabelsMetalYarn         string          `json:"labelsMetalYarn"`
	LabelsProduct           string          `json:"labelsProduct"`
	LabelsTechnics          string          `json:"labelsTechnics"`
	MemosGlass              string          `json:"memosGlass"`
	MemosTechnics           string          `json:"memosTechnics"`
	NamesFanGlass           string          `json:"namesFanGlass"`
	NamesFanYarn            string          `json:"namesFanYarn"`
	NumCorners              int             `json:"numCorners"`
	NumFanGauzes            int             `json:"numFanGauzes"`
	NumFanGlasses           int             `json:"numFanGlasses"`
	NumFanYarns             int             `json:"numFanYarns"`
	NumFrames               int             `json:"numFrames"`
	NumLeafActives          int             `json:"numLeafActives"`
	NumLeafBrights          int             `json:"numLeafBrights"`
	NumLeafBrightsExcCel    int             `json:"numLeafBrightsExcCel"`
	Qh                      int             `json:"qh"`
	Sbtzqh                  int             `json:"sbtzqh"`
	SchemeCustomProps       string          `json:"schemeCustomProps"`
	SectionsHeavyOne        any             `json:"sectionsHeavyOne"`
	SectionsHeavySum        float64         `json:"sectionsHeavySum"`
	SectionsWeight          float64         `json:"sectionsWeight"`
	SectionsWeightAcc       float64         `json:"sectionsWeightAcc"`
	Skbzqh                  int             `json:"skbzqh"`
	TechnicsCustomProps     string          `json:"technicsCustomProps"`
	Variables               Variables       `json:"variables"`
	Version                 string          `json:"version"`
	Xbtzqh                  int             `json:"xbtzqh"`
	Xkbzqh                  int             `json:"xkbzqh"`
}
type DetailFrames struct {
	Bale     string `json:"bale"`
	Detail   string `json:"detail"`
	Formula  string `json:"formula"`
	HostBale string `json:"hostBale"`
	HostID   string `json:"hostID"`
	Value    string `json:"value"`
}
type Packaging struct {
	Bale            string `json:"bale"`
	Deleted         bool   `json:"deleted"`
	Detail          string `json:"detail"`
	FrameID         string `json:"frameId"`
	Group           int    `json:"group"`
	Height          int    `json:"height"`
	HostBale        string `json:"hostBale"`
	ID              string `json:"id"`
	Label           string `json:"label"`
	LeafBale        string `json:"leafBale,omitempty"`
	LeafJgh         int    `json:"leafJgh,omitempty"`
	LeafJgw         int    `json:"leafJgw,omitempty"`
	MainMetalID     string `json:"mainMetalID,omitempty"`
	MainMetalLabel  string `json:"mainMetalLabel,omitempty"`
	MainMetalNumber string `json:"mainMetalNumber,omitempty"`
	Mark            string `json:"mark"`
	Modified        bool   `json:"modified"`
	Originate       int    `json:"originate"`
	RulerHeight     int    `json:"rulerHeight,omitempty"`
	RulerWidth      int    `json:"rulerWidth,omitempty"`
	TemSchemeID     string `json:"temSchemeID"`
	TemSchemeLabel  string `json:"temSchemeLabel"`
	TemSchemeNumber string `json:"temSchemeNumber"`
	TemSchemeType   string `json:"temSchemeType"`
	Transh          int    `json:"transh,omitempty"`
	Transw          int    `json:"transw,omitempty"`
	Width           int    `json:"width"`
	Tags            string `json:"tags,omitempty"`
}

type Pack struct {
	Frames     []DetailFrames `json:"frames"`
	HoleNumber string         `json:"holeNumber"`
	PackDesc   string         `json:"packDesc"`
	Packaging  []Packaging    `json:"packaging"`
}
